version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8090:8080
    volumes:
      - /home/centos/filebrowser-data:/data
      - /root/filebrowser-config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always